### PR TITLE
Implemented RFS_listDirectory Methode

### PR DESCRIPTION
**Pull request by Kiefer-M**
- Implemented RFS_listDirectory
- Added class FileSystemEntries to represent file system objects
- Introduced a factory function to construct different RFS_LITDIR_R structures depending on the number of items (File system entries)
- Adapted the tests

### CODE REVIEW

**Comment by Kiefer-M** [comment]
@NeumannSven 
Is this repository still maintained? I didn't get any feedback yet - So i thought it would be best to check in.

**Review by NeumannSven — COMMENTED** [review]
Thanks for implementing the RFS_listDirectory method

**Comment by NeumannSven** [comment]
add RFS_listDirectory method

**Review by NeumannSven — COMMENTED** [review]
add RFS_listDirectory method

**Review by NeumannSven — COMMENTED** [review]
add RFS_listDirectory method

**Comment by Kiefer-M** [comment]
@NeumannSven - Glad to see that the implementation can help the project. 
How are you Handling releases to PyPi ? Just so that a simplified installment process via pip is possible :)

**Pull request merged**
